version: "3.8"
services:
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  gcs:
    image: fsouza/fake-gcs-server:1.52.1
    ports:
      - 4443:4443
    volumes:
      - ${PWD}/tmp/gcs:/storage
    command: -scheme http