package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"

	"github.com/reearth/scaffold/server/internal/transport/gql/gqlmodel"
)

// Node is the resolver for the Node field.
func (r *queryResolver) Node(ctx context.Context, id gqlmodel.ID) (gqlmodel.Node, error) {
	panic(fmt.Errorf("not implemented: Node - Node"))
}

// Nodes is the resolver for the Nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []gqlmodel.ID) ([]gqlmodel.Node, error) {
	panic(fmt.Errorf("not implemented: Nodes - Nodes"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
