package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/reearth/scaffold/server/internal/transport/gql/gqlmodel"
)

// Workspaces is the resolver for the workspaces field.
func (r *meResolver) Workspaces(ctx context.Context, obj *gqlmodel.Me) (*gqlmodel.WorkspaceConnection, error) {
	panic(fmt.Errorf("not implemented: Workspaces - workspaces"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlmodel.Me, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, email string) (*gqlmodel.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Me returns MeResolver implementation.
func (r *Resolver) Me() MeResolver { return &meResolver{r} }

type meResolver struct{ *Resolver }
