// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cliapp

import (
	"context"
	"github.com/reearth/server-scaffold/internal/transport/cli"
)

// Injectors from wire.go:

func InitializeCLI(ctx context.Context, conf cli.Config) (*cli.CLI, error) {
	cliCLI := cli.NewCLI(conf)
	return cliCLI, nil
}
