on:
  workflow_call:
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run coverage
      # - name: Send coverage report
      #   uses: codecov/codecov-action@v4
      #   with:
      #     flags: web
      # - name: Check translations
      #   run: pnpm run i18n --fail-on-update
      - name: Build
        run: pnpm run build
      - name: Pack
        if: github.ref_name == 'main' || github.ref_name == 'release'
        run: tar -zcvf dist.tar.gz dist
      - uses: actions/upload-artifact@v4
        if: github.ref_name == 'main' || github.ref_name == 'release'
        with:
          name: dist
          path: web/dist.tar.gz
          if-no-files-found: error
