on:
  workflow_call:
jobs:
  nginx-config-validation:
    uses: reearth/actions/.github/workflows/validate-nginx-config.yml@e05fcd1efc6c985c7c0c906cff1452ee634232c8
    with:
      template_directory: docker
      template_values: '{"PORT": 8080, "REAL_IP_HEADER": "X-Forwarded-For"}'
      working_directory: web
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: web/package.json
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: web
      - name: Lint
        run: pnpm run lint
        working-directory: web
      - name: Test
        run: pnpm run coverage
        working-directory: web
      # - name: Send coverage report
      #   uses: codecov/codecov-action@v4
      #   with:
      #     flags: web
      - name: Check translations
        run: pnpm run i18n --fail-on-update
        working-directory: web/apps
      - name: Build
        run: pnpm run build
        working-directory: web/apps
      - name: Pack
        if: github.ref_name == 'main' || github.ref_name == 'release'
        run: tar -zcvf dist.tar.gz dist
        working-directory: web/apps
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: github.ref_name == 'main' || github.ref_name == 'release'
        with:
          name: dist
          path: web/apps/dist.tar.gz
          if-no-files-found: error
