on:
  workflow_call:
jobs:
  nginx-config-validation:
    uses: reearth/actions/.github/workflows/validate-nginx-config.yml@ecb4231198dc0992c3f69c333ee9748ec50ee8a4
    with:
      template_directory: docker
      template_values: '{"PORT": 8080, "REAL_IP_HEADER": "X-Forwarded-For"}'
      working_directory: web
  ci:
    name: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          package_json_file: web/package.json
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run coverage
      # - name: Send coverage report
      #   uses: codecov/codecov-action@v4
      #   with:
      #     flags: web
      # - name: Check translations
      #   run: pnpm run i18n --fail-on-update
      - name: Build
        run: pnpm run build
      - name: Pack
        if: github.ref_name == 'main' || github.ref_name == 'release'
        run: tar -zcvf dist.tar.gz dist
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: github.ref_name == 'main' || github.ref_name == 'release'
        with:
          name: dist
          path: web/dist.tar.gz
          if-no-files-found: error
