on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Next version (NOTE: Switch the branch to "release"!)'
        type: choice
        default: minor
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: reearth/actions/release@c1576f047634cc9d171eaed269d64e3c852ab984
        with:
          version: ${{ inputs.version }}
