on:
  workflow_dispatch:

jobs:
  stage:
    name: Stage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: reearth/actions/stage@c1576f047634cc9d171eaed269d64e3c852ab984
