on:
  workflow_dispatch:

jobs:
  stage:
    name: Stage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: reearth/actions/stage@c6793ef5c58aaf8de8d8327b7e2f0852c096f775
