version: "3"
services:
  reearth-flow-ui:
    image: reearth/scaffold-web:latest
    build:
      context: ..
      dockerfile: web/Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - apps/.env